name: ci
on: [push, pull_request]
jobs:
  uji:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.3.0
        with: { python-version: "3.12.8" }
      - run: pip install -r requirements.txt
      - run: python -m pytest -q
      - run: python -m ruff check src
